[Task] Criar componente wrapper live shop
commerce-suite/storefront-components pull request #14
Opened 2024-09-23 17:06 UTC by Fabriciocaldana

## [Task] Criar componente wrapper live shop

### Changes:

- Criação de todo wrapper da live shop com mock.

2024-09-24 15:04 UTC, simaomeyrerdooca requested changes

2024-09-24 15:04 UTC, simaomeyrerdooca commented on src/components/live-shop/live-shop.tsx
> +  private renderInLiveDesktop() {
Talvez podemos criar componentes separados para as visões de mobile e desktop para deixar esse arquivo mais limpo, o que acha?

2024-10-01 12:10 UTC, Fabriciocaldana commented on src/components/live-shop/live-shop.tsx
> +  private renderInLiveDesktop() {
@simaomeyrerdooca Feito, criei dois snippets pra mobile/desktop

2024-10-02 18:49 UTC, simaomeyrerdooca approved these changes

2024-10-02 19:12 UTC, andrew-sobrera-bagy approved these changes

2024-10-02 19:41 UTC, gabrielwdooca approved these changes

2024-10-02 19:44 UTC, merged