[Task] Adicionar aviso caso não exista uma live ativa
commerce-suite/storefront-components pull request #21
Opened 2024-11-14 14:38 UTC by Fabriciocaldana

## [Task] Adicionar aviso caso não exista uma live ativa

[task link](https://dev.azure.com/doocacom/Platform/_workitems/edit/19339)

### Changes:

- Adiciona tela de live não encontrada.

<img width="1440" alt="Captura de Tela 2024-11-14 às 11 37 54" src="https://github.com/user-attachments/assets/b007dcc7-e6a6-4391-8aa3-85ddc7c4daca">

2024-11-14 16:36 UTC, simaomeyrerdooca requested changes

2024-11-14 16:36 UTC, simaomeyrerdooca commented on src/components/live-shop/live-shop.tsx
> +        <Host>
podemos criar como um snippet separado esse component

2024-11-14 18:04 UTC, Fabriciocaldana commented on src/components/live-shop/live-shop.tsx
> +        <Host>
feito

2024-11-14 18:08 UTC, simaomeyrerdooca approved these changes

2024-11-18 12:03 UTC, LucasPiccinini approved these changes

2024-11-18 12:28 UTC, merged