[Task] Criar componente dedicado para prices
commerce-suite/storefront-components pull request #24
Opened 2024-12-16 14:36 UTC by Fabriciocaldana

## [Task] Criar componente dedicado para prices

[task link](https://dev.azure.com/doocacom/Platform/_workitems/edit/20078)

### Changes:

- Adição de novo componente para exibição de preços do product-card;
- Adição de prop para exibir preço simples ou não.

2024-12-16 17:09 UTC, gabrielwdooca approved these changes

2024-12-17 20:55 UTC, simaomeyrerdooca requested changes

2024-12-17 20:55 UTC, simaomeyrerdooca commented on dist/types/components/ui/product-card/product-card.d.ts
> +    paymentOptions: IPaymentOption[];
em projetos que ainda temos opção, vamos remover o prefixo `I`

2024-12-17 20:55 UTC, simaomeyrerdooca commented on src/components/ui/product-price/product-price.tsx
> +  @Prop() paymentOptions: IPaymentOption[] = [];
acho que essa prop pode ser opcional, caso ela não seja passada usamos o preço normal

2024-12-17 20:55 UTC, simaomeyrerdooca commented on src/components/ui/product-price/product-price.tsx
> +  private renderStrategy = {
nesse contexto não vejo problema em fazermos componentes separados, um para cada método por conta da lógica

2024-12-18 12:22 UTC, Fabriciocaldana commented on dist/types/components/ui/product-card/product-card.d.ts
> +    paymentOptions: IPaymentOption[];
feito

2024-12-18 12:22 UTC, Fabriciocaldana commented on src/components/ui/product-price/product-price.tsx
> +  @Prop() paymentOptions: IPaymentOption[] = [];
deixei ela como opcional, mas na falta dela, é obrigatório enviar o basePrice

2024-12-18 12:22 UTC, Fabriciocaldana commented on src/components/ui/product-price/product-price.tsx
> +  private renderStrategy = {
feito

2024-12-18 20:38 UTC, simaomeyrerdooca commented on dist/types/components.d.ts
> +        "price"?: number;
`ProductPriceSimple` pode ser a interface base e todas as outras estendem dela

2024-12-19 11:59 UTC, Fabriciocaldana commented on dist/types/components.d.ts
> +        "price"?: number;
feito

2024-12-19 12:02 UTC, simaomeyrerdooca approved these changes

2024-12-19 12:03 UTC, merged