[Task] Componente de aguardando a live
commerce-suite/storefront-components pull request #6
Opened 2024-07-05 18:15 UTC by Fabriciocaldana

## [Task] Componente de aguardando a live

[task link](https://dev.azure.com/doocacom/Platform/_workitems/edit/15240)
[task link](https://dev.azure.com/doocacom/Platform/_workitems/edit/15241)

### Changes:

- Cria componente genérico para usar como card.

2024-07-05 18:23 UTC, simaomeyrerdooca requested changes

2024-07-05 18:23 UTC, simaomeyrerdooca commented on src/components/custom-card/custom-card.scss
> +      max-width: 410px;
acho que aqui podemos deixar sem max, quem vai dar o tamanho dele sempre vai ser quem o utiliza

2024-07-05 18:28 UTC, Fabriciocaldana commented on src/components/custom-card/custom-card.scss
> +      max-width: 410px;
@simaomeyrerdooca feito

2024-07-08 12:00 UTC, simaomeyrerdooca approved these changes

2024-07-08 12:25 UTC, ryanlaiber approved these changes

2024-07-08 13:28 UTC, tiagotermebagy commented on src/components/custom-card/custom-card.tsx
> +  @Prop() cardTitle: string = 'Não perca! Live hoje às 19 horas.';
Faz sentido ter o prefixo card nas props?

2024-07-08 13:28 UTC, tiagotermebagy commented on src/components/custom-card/custom-card.tsx
> +  @Prop() cardPadding: string = '88px 0';
as props de margin e padding são necessárias?

2024-07-08 13:35 UTC, Fabriciocaldana commented on src/components/custom-card/custom-card.tsx
> +  @Prop() cardTitle: string = 'Não perca! Live hoje às 19 horas.';
@tiagotermebagy eu adicionei porque title é uma palavra reservada, mas daria pra achar um nome melhor

2024-07-08 13:36 UTC, Fabriciocaldana commented on src/components/custom-card/custom-card.tsx
> +  @Prop() cardPadding: string = '88px 0';
@tiagotermebagy não são, vou remover

2024-07-08 14:30 UTC, merged